# .gitpod.yml

image: gitpod/workspace-python-3.9

tasks:
  - name: "Set up Python"
    command: |
      pyenv install 3.9.6
      pyenv global 3.9.6
      pip install --upgrade pip
      pip install -r requirements.txt

  - name: "Start MySQL"
    init: |
      # Start MySQL container with a persistent volume
      docker run --name mysql-container \
        -e MYSQL_ROOT_PASSWORD=thisissecurepassword \
        -v /workspace/mysql_data:/var/lib/mysql \
        -p 3306:3306 \
        -d mysql:latest

    command: |
      # Wait for MySQL service to be up and running
      while ! docker logs mysql-container 2>&1 | grep "ready for connections"; do
        echo "Waiting for MySQL to be up..."
        sleep 1
      done
      echo "MySQL is up and running!"
