# .gitpod.yml

image: 
  file: .gitpod.Dockerfile

tasks:
  - name: "Set up .env_docker"
    command: |
      echo "DEVELOPER_NAME=matias" >> backend/.env_docker
      echo "TIDB_HOST=gateway01.us-east-1.prod.aws.tidbcloud.com" >> backend/.env_docker
      echo "TIDB_USERNAME=6K9ZXKTM8XD1n73.root" >> backend/.env_docker
      echo "TIDB_PORT=4000" >> backend/.env_docker
      echo "TIDB_DB_NAME=test_matias" >> backend/.env_docker
      echo "MYSQL_HOST=mysql-container" >> backend/.env_docker
      echo "MYSQL_USERNAME=root" >> backend/.env_docker
      echo "MYSQL_PASSWORD=my-secret-pw" >> backend/.env_docker
      echo "MYSQL_PORT=3306" >> backend/.env_docker
      echo "MYSQL_DB_NAME=docker_test" >> backend/.env_docker
      echo "PYTHONPATH=./backend" >> backend/.env_docker
      echo "FASTAPI_HOST=0.0.0.0" >> backend/.env_docker
      echo "FASTAPI_PORT=8000" >> backend/.env_docker

  - name: "Set React API Base URL"
    command: |
      # Insert the port number after 'https://'
      export REACT_APP_API_BASE_URL=$(echo $GITPOD_WORKSPACE_URL | sed -e 's#https://#https://8000-#')
      echo "REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}" >> frontend/lamatidb/.env
      export REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}

  - name: "Create Network"
    command: |
      # Create Network do docker-compose can find it
      docker network create mynetwork || true
  
  - name: "Start Docker Compose Services"
    init: |
      # Collect TiDB password
      read -s -p 'Enter TiDB Password: ' TIDB_PASSWORD && echo "" && echo "TIDB_PASSWORD=$TIDB_PASSWORD" >> backend/.env_docker

      # Build and start all services defined in the docker-compose.yml
      docker-compose up --build -d

    command: |
      # Wait for MySQL to be up and running (optional)
      while ! docker logs mysql-container 2>&1 | grep "ready for connections"; do
        echo "Waiting for MySQL to be up..."
        sleep 1
      done
      echo "MySQL is up and running!"
      sudo chmod -R 777 /workspace/pico-scholar/backend/mysql_data/

ports:
  - port: 3000
    onOpen: open-preview
