# Stage 1: Install dependencies
FROM python:3.9 AS pico-env-builder

# Set the working directory in the container
WORKDIR /app

# Copy only requirements.txt first, to leverage Docker cache
COPY requirements.txt /app/

# Install dependencies
RUN pip install --upgrade pip && \
    pip install  --no-cache-dir -r requirements.txt

# Install Model dependencies
# CMD ["python", "pipelines/prepare_model.py"]