# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentIdChatBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, question: str=None):  # noqa: E501
        """DocumentIdChatBody - a model defined in Swagger

        :param question: The question of this DocumentIdChatBody.  # noqa: E501
        :type question: str
        """
        self.swagger_types = {
            'question': str
        }

        self.attribute_map = {
            'question': 'question'
        }
        self._question = question

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentIdChatBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The documentId_chat_body of this DocumentIdChatBody.  # noqa: E501
        :rtype: DocumentIdChatBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question(self) -> str:
        """Gets the question of this DocumentIdChatBody.

        The natural language question  # noqa: E501

        :return: The question of this DocumentIdChatBody.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question: str):
        """Sets the question of this DocumentIdChatBody.

        The natural language question  # noqa: E501

        :param question: The question of this DocumentIdChatBody.
        :type question: str
        """

        self._question = question
