# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FunnelReviewedBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, record_ids: List[str]=None, reviewed: bool=None):  # noqa: E501
        """FunnelReviewedBody - a model defined in Swagger

        :param record_ids: The record_ids of this FunnelReviewedBody.  # noqa: E501
        :type record_ids: List[str]
        :param reviewed: The reviewed of this FunnelReviewedBody.  # noqa: E501
        :type reviewed: bool
        """
        self.swagger_types = {
            'record_ids': List[str],
            'reviewed': bool
        }

        self.attribute_map = {
            'record_ids': 'recordIds',
            'reviewed': 'reviewed'
        }
        self._record_ids = record_ids
        self._reviewed = reviewed

    @classmethod
    def from_dict(cls, dikt) -> 'FunnelReviewedBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The funnel_reviewed_body of this FunnelReviewedBody.  # noqa: E501
        :rtype: FunnelReviewedBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def record_ids(self) -> List[str]:
        """Gets the record_ids of this FunnelReviewedBody.


        :return: The record_ids of this FunnelReviewedBody.
        :rtype: List[str]
        """
        return self._record_ids

    @record_ids.setter
    def record_ids(self, record_ids: List[str]):
        """Sets the record_ids of this FunnelReviewedBody.


        :param record_ids: The record_ids of this FunnelReviewedBody.
        :type record_ids: List[str]
        """

        self._record_ids = record_ids

    @property
    def reviewed(self) -> bool:
        """Gets the reviewed of this FunnelReviewedBody.

        Reviewed marker (true/false)  # noqa: E501

        :return: The reviewed of this FunnelReviewedBody.
        :rtype: bool
        """
        return self._reviewed

    @reviewed.setter
    def reviewed(self, reviewed: bool):
        """Sets the reviewed of this FunnelReviewedBody.

        Reviewed marker (true/false)  # noqa: E501

        :param reviewed: The reviewed of this FunnelReviewedBody.
        :type reviewed: bool
        """

        self._reviewed = reviewed
