# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FunnelStatusBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, record_ids: List[str]=None, new_status: str=None):  # noqa: E501
        """FunnelStatusBody - a model defined in Swagger

        :param record_ids: The record_ids of this FunnelStatusBody.  # noqa: E501
        :type record_ids: List[str]
        :param new_status: The new_status of this FunnelStatusBody.  # noqa: E501
        :type new_status: str
        """
        self.swagger_types = {
            'record_ids': List[str],
            'new_status': str
        }

        self.attribute_map = {
            'record_ids': 'recordIds',
            'new_status': 'newStatus'
        }
        self._record_ids = record_ids
        self._new_status = new_status

    @classmethod
    def from_dict(cls, dikt) -> 'FunnelStatusBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The funnel_status_body of this FunnelStatusBody.  # noqa: E501
        :rtype: FunnelStatusBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def record_ids(self) -> List[str]:
        """Gets the record_ids of this FunnelStatusBody.


        :return: The record_ids of this FunnelStatusBody.
        :rtype: List[str]
        """
        return self._record_ids

    @record_ids.setter
    def record_ids(self, record_ids: List[str]):
        """Sets the record_ids of this FunnelStatusBody.


        :param record_ids: The record_ids of this FunnelStatusBody.
        :type record_ids: List[str]
        """

        self._record_ids = record_ids

    @property
    def new_status(self) -> str:
        """Gets the new_status of this FunnelStatusBody.

        New status to apply to the records  # noqa: E501

        :return: The new_status of this FunnelStatusBody.
        :rtype: str
        """
        return self._new_status

    @new_status.setter
    def new_status(self, new_status: str):
        """Sets the new_status of this FunnelStatusBody.

        New status to apply to the records  # noqa: E501

        :param new_status: The new_status of this FunnelStatusBody.
        :type new_status: str
        """

        self._new_status = new_status
