# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryIdSearchBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, search_query: str=None, metadata: Dict[str, str]=None):  # noqa: E501
        """QueryIdSearchBody - a model defined in Swagger

        :param search_query: The search_query of this QueryIdSearchBody.  # noqa: E501
        :type search_query: str
        :param metadata: The metadata of this QueryIdSearchBody.  # noqa: E501
        :type metadata: Dict[str, str]
        """
        self.swagger_types = {
            'search_query': str,
            'metadata': Dict[str, str]
        }

        self.attribute_map = {
            'search_query': 'searchQuery',
            'metadata': 'metadata'
        }
        self._search_query = search_query
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'QueryIdSearchBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The queryId_search_body of this QueryIdSearchBody.  # noqa: E501
        :rtype: QueryIdSearchBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def search_query(self) -> str:
        """Gets the search_query of this QueryIdSearchBody.

        The natural language search query  # noqa: E501

        :return: The search_query of this QueryIdSearchBody.
        :rtype: str
        """
        return self._search_query

    @search_query.setter
    def search_query(self, search_query: str):
        """Sets the search_query of this QueryIdSearchBody.

        The natural language search query  # noqa: E501

        :param search_query: The search_query of this QueryIdSearchBody.
        :type search_query: str
        """

        self._search_query = search_query

    @property
    def metadata(self) -> Dict[str, str]:
        """Gets the metadata of this QueryIdSearchBody.

        Optional metadata to refine the search  # noqa: E501

        :return: The metadata of this QueryIdSearchBody.
        :rtype: Dict[str, str]
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Dict[str, str]):
        """Sets the metadata of this QueryIdSearchBody.

        Optional metadata to refine the search  # noqa: E501

        :param metadata: The metadata of this QueryIdSearchBody.
        :type metadata: Dict[str, str]
        """

        self._metadata = metadata
